"""add_meeting_url_to_mentors

Revision ID: 030d3da2a018
Revises: 1777aef60e4e
Create Date: 2026-07-22 21:30:11.771558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '030d3da2a018'
down_revision: Union[str, Sequence[str], None] = '1777aef60e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentors', sa.Column('meeting_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentors', 'meeting_url')
    # ### end Alembic commands ###
