"""Added missing Gender Field to mentor_application model

Revision ID: 0950f15360cb
Revises: 8dc4a8fcf739
Create Date: 2026-07-02 13:29:00.920821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0950f15360cb'
down_revision: Union[str, Sequence[str], None] = '8dc4a8fcf739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentor_applications', sa.Column('gender', sa.Enum('m', 'f', name='gender_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentor_applications', 'gender')
    # ### end Alembic commands ###
