"""add_phone_number_to_mentor_applications

Revision ID: 11b568adb628
Revises: 1de75f5834f2
Create Date: 2026-06-30 17:52:07.469258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b568adb628'
down_revision: Union[str, Sequence[str], None] = '1de75f5834f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentor_applications', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentor_applications', 'phone_number')
    # ### end Alembic commands ###
