"""add_major_experience_to_mentors

Revision ID: 1777aef60e4e
Revises: 91f25a7bbc7c
Create Date: 2026-07-21 21:53:25.658693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1777aef60e4e'
down_revision: Union[str, Sequence[str], None] = '91f25a7bbc7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_user_id', sa.Integer(), nullable=False),
    sa.Column('mentor_user_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='recommendation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mentor_user_id'], ['mentors.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_user_id'], ['students.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('mentors', sa.Column('major', sa.String(length=255), nullable=True))
    op.add_column('mentors', sa.Column('experience', sa.String(length=255), nullable=True))
    op.alter_column('tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_tag_name_category'), 'tags', type_='unique')
    op.create_index(op.f('ix_tags_category'), 'tags', ['category'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_category'), table_name='tags')
    op.create_unique_constraint(op.f('uq_tag_name_category'), 'tags', ['name', 'category'], postgresql_nulls_not_distinct=False)
    op.alter_column('tags', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('mentors', 'experience')
    op.drop_column('mentors', 'major')
    op.drop_table('mentor_recommendations')
    # ### end Alembic commands ###
