"""add mentor application fields

Revision ID: 1c5da7f0eb5c
Revises: 6dc01b69a97d
Create Date: 2026-06-17 23:21:28.080975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c5da7f0eb5c'
down_revision: Union[str, Sequence[str], None] = '6dc01b69a97d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentors', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('mentors', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('mentors', sa.Column('company', sa.String(), nullable=True))
    op.add_column('mentors', sa.Column('bio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentors', 'bio')
    op.drop_column('mentors', 'company')
    op.drop_column('mentors', 'job_title')
    op.drop_column('mentors', 'tags')
    # ### end Alembic commands ###
