"""add tag and matching tables

Revision ID: 4ea0a027d7e4
Revises: 0950f15360cb
Create Date: 2026-07-15 21:07:54.007100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea0a027d7e4'
down_revision: Union[str, Sequence[str], None] = '0950f15360cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_category'), 'tags', ['category'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('mentor_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_user_id', sa.Integer(), nullable=False),
    sa.Column('mentor_user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='recommendation_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mentor_user_id'], ['mentors.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_user_id'], ['students.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_recommendations_mentor_user_id'), 'mentor_recommendations', ['mentor_user_id'], unique=False)
    op.create_index(op.f('ix_mentor_recommendations_student_user_id'), 'mentor_recommendations', ['student_user_id'], unique=False)
    op.create_table('mentor_tags',
    sa.Column('mentor_user_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_user_id'], ['mentors.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mentor_user_id', 'tag_id')
    )
    op.create_table('student_tags',
    sa.Column('student_user_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_user_id'], ['students.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_user_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_tags')
    op.drop_table('mentor_tags')
    op.drop_index(op.f('ix_mentor_recommendations_student_user_id'), table_name='mentor_recommendations')
    op.drop_index(op.f('ix_mentor_recommendations_mentor_user_id'), table_name='mentor_recommendations')
    op.drop_table('mentor_recommendations')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_category'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
