"""make_meeting_slot_id_nullable

Revision ID: 6e8ec046f25e
Revises: f4331604ce1f
Create Date: 2026-08-04 12:02:11.421779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8ec046f25e'
down_revision: Union[str, Sequence[str], None] = 'f4331604ce1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'slot_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'slot_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
