"""add_phone_number_to_mentor_table

Revision ID: 8dc4a8fcf739
Revises: d520093bf2a9
Create Date: 2026-07-01 10:33:20.336095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc4a8fcf739'
down_revision: Union[str, Sequence[str], None] = 'd520093bf2a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentors', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentors', 'phone_number')
    # ### end Alembic commands ###
