"""change tag uniqueness constraint

Revision ID: bcbb94f5b2af
Revises: 4ea0a027d7e4
Create Date: 2026-07-16 10:01:28.922798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcbb94f5b2af'
down_revision: Union[str, Sequence[str], None] = '4ea0a027d7e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.create_unique_constraint('uq_tag_name_category', 'tags', ['name', 'category'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tag_name_category', 'tags', type_='unique')
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    # ### end Alembic commands ###
