"""new schema

Revision ID: c4bcc614c281
Revises: 
Create Date: 2026-06-17 22:31:40.223534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4bcc614c281'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'mentor', 'student', name='role_enum'), nullable=False),
    sa.Column('gender', sa.Enum('m', 'f', name='gender_enum'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('mentor_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('employer', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('major', sa.String(length=255), nullable=True),
    sa.Column('alma_mater', sa.String(length=255), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('other_info', sa.Text(), nullable=True),
    sa.Column('service_types', postgresql.ARRAY(postgresql.ENUM('mock_interview', 'resume_review', 'career_advice', name='service_type_enum')), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='application_status_enum'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentors',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gender', postgresql.ENUM('m', 'f', name='gender_enum'), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('employer', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('alma_mater', sa.String(length=255), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('service_types', postgresql.ARRAY(postgresql.ENUM('mock_interview', 'resume_review', 'career_advice', name='service_type_enum')), server_default='{}', nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('max_monthly_sessions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('students',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('major', sa.Text(), nullable=True),
    sa.Column('education_level', sa.Enum('high_school', 'undergraduate', 'graduate', name='education_level_enum'), nullable=True),
    sa.Column('academic_standing', sa.Enum('freshman', 'sophomore', 'junior', 'senior', name='academic_standing_enum'), nullable=True),
    sa.Column('resume_url', sa.Text(), nullable=True),
    sa.Column('resume_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('availability_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_datetime > start_datetime', name='chk_slot_valid_duration'),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_slots_mentor_id'), 'availability_slots', ['mentor_id'], unique=False)
    op.create_table('student_intake_forms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('service_type', sa.Enum('mock_interview', 'resume_review', 'career_advice', name='service_type_enum'), nullable=False),
    sa.Column('gender', sa.Enum('m', 'f', name='gender_enum'), nullable=True),
    sa.Column('desired_career', sa.Text(), nullable=True),
    sa.Column('major', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'assigned', 'completed', 'cancelled', name='intake_form_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_intake_forms_student_id'), 'student_intake_forms', ['student_id'], unique=False)
    op.create_table('mentor_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('intake_form_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'cancelled', name='assignment_status_enum'), server_default='active', nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['intake_form_id'], ['student_intake_forms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_active_mentor', 'mentor_assignments', ['mentor_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_index('uq_active_student', 'mentor_assignments', ['student_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('meeting_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', 'no_show', name='meeting_status_enum'), server_default='scheduled', nullable=False),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('meeting_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['mentor_assignments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['slot_id'], ['availability_slots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meetings')
    op.drop_index('uq_active_student', table_name='mentor_assignments', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('uq_active_mentor', table_name='mentor_assignments', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('mentor_assignments')
    op.drop_index(op.f('ix_student_intake_forms_student_id'), table_name='student_intake_forms')
    op.drop_table('student_intake_forms')
    op.drop_index(op.f('ix_availability_slots_mentor_id'), table_name='availability_slots')
    op.drop_table('availability_slots')
    op.drop_table('students')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('mentors')
    op.drop_table('mentor_applications')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
