"""add meeting_url to mentor

Revision ID: f391fa48c654
Revises: 0950f15360cb
Create Date: 2026-07-15 22:21:17.880216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f391fa48c654'
down_revision: Union[str, Sequence[str], None] = '0950f15360cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentors', sa.Column('meeting_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentors', 'meeting_url')
    # ### end Alembic commands ###
